export const TYPE_SERVERS = 'TYPE_SERVERS';

export const SERVERS_REDUCERS = {
  SET_SERVER: 'SET_SERVER',
  UPDATE_SERVERS: 'UPDATE_SERVERS',
  UPDATE_CACHE_SERVERS: 'UPDATE_CACHE_SERVERS',
  FETCH_SERVERS: 'FETCH_SERVER',
  DELETE_SERVER: 'DELETE_SERVER',
  EDIT_SERVER: 'EDIT_SERVER',
  UPDATE_SELECTED_SERVER: 'UPDATE_SELECTED_SERVER',
};
